### ISSUE TITLE
Google Analytics Code

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/DOL-Timesheet#1]
Deploy Google analytics code

**Comment by nmangu** [comment]
The application on an iPad (iOS) is working 'As Expected' and calculating employee's hours that are due. Also calculating overtime as per one and one-half (1.5) times the regular rate of pay in a 40 hour work week. There are screenshots to validate the same that would shortly be updated on the SharePoint.

**Comment by MikePulsiferDOL** [comment]
We are getting metrics.

**Comment by adams-lisa** [comment]
Change is ready to push to prod.  Nischal will provide QA screen shots for CM repository

**Comment by nmangu** [comment]
Hi Lisa

Here is the Link to the GitHub where I’d posted the result for this.

https://github.com/USDepartmentofLabor/DOL-Timesheet/issues/1#issuecomment-127692885


The screenshots will be updated on the SharePoint shortly.

Thank you,

Nischal Mangu
Quality Specialist, Quality Management Team
Department of Labor, Office of Public Affairs
Division of Enterprise Communications
Extn. (202) 693-6583

**Comment by MikePulsiferDOL** [comment]
Validated and submitted to Apple.
